print("90 degrees triangle")
print("___________________")
print("\n"*3)
leg_a = float(input("Please insert the lenght expressed in cm for leg A:"))
leg_b = float(input("Please insert the lenght expressed in cm for leg B:"))
hypo = (leg_a**2+leg_b**2)**0.5
print("\n"*3)
print("Leg A lenght:",end=" ")
print(leg_a)
print()
print()
print("Leg B lenght:",end=" ")
print(leg_b)
print("\n"*2)
print("The lenght of the hypotenuse expressed in cm is equal to",end=" ")
print(hypo)
print()
print()
print("Clear demonstrations, isn't it?")

