SUM_OF_EURO = 1500
SUM_OF_RON = 360
print("We know that 1 euro = 4.98 RON")
print("How much is 1500 EURO expressed in ron?")
print("How much is 360 RON expressed in euros?")
print()
print(SUM_OF_EURO)
print(SUM_OF_RON)
EURO_TO_RON = SUM_OF_EURO * 4.98
RON_TO_EURO = SUM_OF_RON / 4.98
print()
print(round(EURO_TO_RON,2))
print(round(RON_TO_EURO,2))
print()
print()
print(SUM_OF_EURO,"EURO represents",round(EURO_TO_RON,2),"RON")
print(SUM_OF_RON,"RON represents",round(RON_TO_EURO,2),"EURO")
print("\n"*10)
print("____________________")
print("THE \"ROUND\" FUNCTION")
print("````````````````````")
print("\n")
print("In order to display in the console the \"ROUND\" function, we need it to be included in a \"print\" function.")
print("Like so:")
print()
print("Step 1: We define a variable called \"exe\"","and we print it:")
exe = 17.809103
print(exe)
print()
print("Step 2: We input the \"print\" + \"round\" functions togheter like so:")
print()
print("print(round(exe,2))")
print("shows us ----------------->",round(exe,2))
print()
print("print(round(exe,3))")
print("shows us ----------------->",round(exe,3))
print()
print("print(round(exe,4))")
print("shows us ----------------->",round(exe,4))
print()
print("print(round(exe,5))")
print("shows us ----------------->",round(exe,5))
print()
print("print(round(exe,6))")
print("shows us ----------------->",round(exe,6))
print()
print()
print("Remember that the \"exe\" variable is equal to 17.809103")

    

