print("OPERATIONS_______________________________________________________")
print("RUN THIS TO SEE THE RESULTS OF DIFFERENT OPERATIONS WITHIN PYTHON\nby dr1")
print("`````````````````````````````````````````````````````````````````")
print("_________________________________________________________________")
print("\n"*5)
print("________________")
print("BASIC OPERATIONS")
print("````````````````")
print("\n")
print("\"print(10+15)\"","will display:")
print(10+15)
print("\n")
print("\"print(10.1+15)\"","will display:")
print(10.1+15)
print("\n")
print("\"print(10+15.1)\"","will display:")
print(10+15.1)
print("\n")
print("\"print(10.1+15.2)\"","will display:")
print(10.1 + 15.2)
print("\n")
print("\"print(10-15)\"","will display:")
print(10-15)
print("\n")
print("\"print(10.1-15)\"","will display:")
print(10.1-15)
print("\n")
print("\"print(10-15.1)\"","will display:")
print(10-15.1)
print("\n")
print("\"print(10.1-15.1)\"","will display:")
print(10.1-15.1)
print("\n"*17)
print("______________")
print("MULTIPLICATION"," ",sep=":")
print("``````````````")
print("\n"*2)
print("\"print(3*2)\"","\nwill display:")
print(3*2)
print("\n")
print("\"print(3.1*2)\"","\nwill display:")
print(3.1*2)
print("\n")
print("______________")
print("EXPONENTIATION")
print("``````````````")
print("\n")
print("\"print(3**10)\"","\nwill display:")
print(3**10)
print("\n")
print("\"print(3.1**10)\"","\nwill display:")
print(3.1**10)
print("\n"*17)
print("________")
print("DIVISION","!division by 0 gives and error!",sep="      ------      ")
print("````````")
print("\n")
print("\"print(10/2)\"","will display:")
print(10/2)
print("\n")
print("\"print(10.1/2)\"","will display:")
print(10.1/2)
print("\n")
print("\"print(10/2.1)\"","will display:")
print(10/2.1)
print("\n")
print("\"print(10.1/2.1)\"","will display:")
print(10.1/2.1)
print("\n")
print("_________________________________________________")
print("INTEGER DIVISION (also called \"floor division\")","!integer division by 0 gives an error!",sep="      ------      ")
print("`````````````````````````````````````````````````")
print("\n")
print("\"print(10//2)\"","will display:")
print(10//2)
print("\n")
print("\"print(10//2.0)\"","will display:")
print(10//2.0)
print("\n")
print("\"print(10.1//2)\"","will display:")
print(10.1//2)
print("\n")
print("\"print(10.1//2.1)\"","will display:")
print(10.1//2.1)
print("\n")
print("~~~ additional info for INTEGER DIVISION ~~~")
print("\n")
print("We know that the rounding is done to the closest lowest integer when using the floor division")
print("Therefore,we have the following examples in the case of negative results displayed:")
print("\n")
print("\"print(-10//2.1)\"","will display:")
print(-10//2.1)
print("Mathematically, -10/2.1 = -4.76/nas said, since we have negative results, the displayed\noutput will be rounded to the lowest integer but including the .0 since the operations itself contains .0")
print("\n")
print("______")
print("MODULO (also called \"remainder\")","!modulo division by 0 gives an error!",sep="      ------      ")
print("``````")
print("\n")
print("\"print(14%4)\"","will display:")
print(14%4)
print("Basically, the modulo is the remainder of the division")
print("Mathematically, (+python calculus), 14 // 4 = 3 (+ with remainder 2) \n--> 4 * 3 = 12; 14 - 12 = 2 (the remainder)")
print("\n")
print("\"print(14%4.5)\"","will display:")
print(14%4.5)
print("Mathematically, (+python calculus), 14 // 4.5 = 3.0 (+ with remainder 0.5) \n--> 4.5 * 3 = 13.5; 14 - 13.5 = 0.5 (the remainder)")
print("\n")
print("\"print(-21%4)\"","will display:")
print(-21%4)
print("Mathematically, (+python calculus), -21 // 4 = -6 (+ with remainder 3) \n--> 4 * -6 = -24; -21 - -24 = 3 (the remainder)")
print("\n")
print("\"print(-21%4.5)\"","will display:")
print(-21%4.5)
print("Mathematically, (+python calculus), -21 // 4.5 = -5.0 (+remainder of 1.5) \n--> 4.5 * -5.0 = -22.5; -21 - -22.5 = 1.5 (the remainder)")
print("\n")
print("\"print(-21%-4.5)\"","will display:")
print(-21%-4.5)
print("Mathematically, (+python calculus), -21 // -4.5 = 4.0 (+remainder of -3.0) \n--> -4.5 * 4.0 = -18.0; -21 - -18.0 = -3.0 (the remainder)")
print("\n"*17)
print("____________","\nEXTRA THINGS")
print("````````````")
print("\n")
print("You can add parantheses like this","\nAlso, the order of operations from mathematics will always apply")
print("\n")
print("\"print((10.7 * 2) // (10 ** 2 -10) + (82 * 3))\"","will display:")
print((10.7 * 2) // (10 ** 2 -10) + (82 * 3))





      
      
